### ISSUE TITLE
please add to maven central for gradle usage

### ISSUE THREAD

**Issue by kenyee** [MoraisIgor/SlidingDrawer#3]
Would be great if we can just add this to gradle...

**Comment by commonsguy** [comment]
Whether it is Maven Central, JCenter, or your own repo, I agree that this really should be an artifact in a repository.

**Comment by MoraisIgor** [comment]
Working on it now.

**Comment by man4ik** [comment]
Any progress?

**Comment by MoraisIgor** [comment]
Sorry for delay in response.

I have uploaded to jCenter and Maven.

Put this in dependencies: `compile 'com.github.moraisigor:slidingdrawer:1.5.1'`

I have updated the read me and sample app too. Soon ill put on the play store.

[]'s
